server:
  port: 9400
eureka:
  server: 
    enable-self-preservation: false #是否开启自我保护模式
  instance: 
    hostname: 192.168.1.121
  client:
    registerWithEureka: false #注册中心是否注册资金
    fetchRegistry: false #是否检索服务
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/